#34 add web services.
officel/spelling-dictionary pull request #35
Opened 2016-12-15 17:37 UTC by officel

@keika299 レビューお願いします！

2016-12-15 17:50 UTC, ezaki requested changes
livedoor が webservice に含まれるかどうかについての議論が必要かと思います。

2016-12-15 17:50 UTC, keika299 commented on dictionaries/webservice/webservice.yaml
> +  - word: livedoor
livedoor は webservice に入りますか？

私としては、プログラマが利用する cloud service をイメージしていますので、
この項目については website などの別項を設けても良いと思います。

2016-12-15 17:58 UTC, officel commented on dictionaries/webservice/webservice.yaml
> +  - word: livedoor
website を別途用意するのはやぶさかではないです。
livedoor を置いた理由としては
* yahoo, google 等は typo にならない
* APIサービスがある（こういうの） -> http://weather.livedoor.com/weather_hacks/
* そしてそれを個人的に使っている（のでコメント等々TYPOが頻発している）
* website の追加は数と選定ルール決めで遅延する気がする
って感じです。

2016-12-15 18:11 UTC, ezaki requested changes
livedoor の概要に対して、API提供についても触れるようにするのはいかがでしょうか。

2016-12-15 18:11 UTC, keika299 commented on dictionaries/webservice/webservice.yaml
> +  - word: livedoor
理解しました。

別々にすると、確かにその選定ルールが必要になるので、こちらに追加でいきましょう。

2016-12-15 18:11 UTC, keika299 commented on dictionaries/webservice/webservice.yaml
> +    description: portal site.
webservice に追加する理由として、APIサービスを持っていることが挙げられているので、
```
description: portal site and api vendor.
```

とすることを提案します。

2016-12-15 23:59 UTC, officel reviewed
提案いただいたとおり入れてみました！

2016-12-16 03:33 UTC, ezaki approved these changes
ありがとうございます！
OKでーす

2016-12-16 05:26 UTC, merged